name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Check Devcontainer Conformity
      run: |
        if [ -f ".devcontainer/Dockerfile" ]; then
          docker build .devcontainer --tag devcontainer-test:latest
          echo "Devcontainer Dockerfile build succeeded."
        else
          echo "No Devcontainer Dockerfile found. Skipping build check."
        fi